


"""Train an XGBoost regressor on the mock transport-cost dataset and save it
as a .pkl file for routers/logistics.py to load at inference time.

Features are deliberately limited to distance_km and payload_kg — the only
two predictive columns CostEstimateRequest (models/schemas.py) actually
carries. The mock data also varies cost by crop_type and road_condition
(agritech_transport_data_mock.csv, generated by generate_mock_data.py), but
neither reaches this endpoint today, so the model can't see them either.
"""

import pickle
from pathlib import Path

import numpy as np
import pandas as pd
from xgboost import XGBRegressor

DATA_PATH = Path(__file__).resolve().parent.parent / "agritech_transport_data_mock.csv"
MODEL_PATH = Path(__file__).resolve().parent / "cost_model.pkl"
FEATURES = ["distance_km", "payload_kg"]
TARGET = "actual_cost_ghs"


def main() -> None:
    df = pd.read_csv(DATA_PATH)

    rng = np.random.default_rng(42)
    shuffled = rng.permutation(len(df))
    split = int(len(df) * 0.8)
    train_idx, test_idx = shuffled[:split], shuffled[split:]

    X_train, y_train = df.loc[train_idx, FEATURES], df.loc[train_idx, TARGET]
    X_test, y_test = df.loc[test_idx, FEATURES], df.loc[test_idx, TARGET]

    model = XGBRegressor(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.1,
        random_state=42,
    )
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)
    mae = float(np.mean(np.abs(predictions - y_test)))
    mape = float(np.mean(np.abs((predictions - y_test) / y_test)) * 100)
    print(f"Test MAE:  {mae:.2f} GHS")
    print(f"Test MAPE: {mape:.1f}%")

    with open(MODEL_PATH, "wb") as f:
        pickle.dump({"model": model, "features": FEATURES}, f)
    print(f"Saved model to {MODEL_PATH}")


if __name__ == "__main__":
    main()
